AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Py Spotty api'

Parameters:
  DEBUG:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
  SpotifyClientId:
    Type: String
    Default: '{{resolve:ssm:JafSpotifyClientId:1}}'
    AllowedValues:
      - '{{resolve:ssm:JafSpotifyClientId:1}}'
  SpotifyClientSecret:
    Type: String
    Default: '{{resolve:ssm:JafSpotifySecret:1}}'
    AllowedValues:
      - '{{resolve:ssm:JafSpotifySecret:1}}'
  JwtSecret:
    Type: String
    Default: '{{resolve:ssm:JafJwtSecret:1}}'
    AllowedValues:
      - '{{resolve:ssm:JafJwtSecret:1}}'

Globals:
  Function:
    Timeout: 15
    MemorySize: 128
    Runtime: python3.9
    Environment:
      Variables:
        DEBUG: !Ref DEBUG
        SpotifyClientId: !Ref SpotifyClientId
        SpotifyClientSecret: !Ref SpotifyClientSecret
        JwtSecret: !Ref JwtSecret

Resources:
  HttpApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
      Cors:
        AllowHeaders: "*"
        AllowMethods: "*"
        AllowOrigin: "*"
      # Domain:
      #   DomainName: py-userquiz.jaf-unwrapped.com
      #   # CertificateArn: arn:aws:acm:ap-southeast-2:355151872526:certificate/12c34da1-c039-4fc4-9636-05571fdb3df9
      #   CertificateArn: arn:aws:acm:eu-west-2:355151872526:certificate/692a3b22-81bb-4c1c-a600-a1eac3cb32cb
      #   Route53:
      #     HostedZoneId: Z05897963LYPVXX455E44

  LoadQuizFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: functions/quiz.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: SpotifyQuiz
        - DynamoDBCrudPolicy:
            TableName: SpotifyQuizResponse
      Events:
        GetLoadQuiz:
          Type: Api
          Properties:
            Path: /quiz/{type}
            Method: get
            RestApiId: !Ref HttpApiGateway
            RequestParameters:
              - method.request.path.type:
                  Required: true
              - method.request.querystring.id:
                  Required: true
              - method.request.header.Authorization:
                  Required: true
        OptionsLoadQuiz:
          Type: Api
          Properties:
            Path: /quiz/{type}
            Method: options
            RestApiId: !Ref HttpApiGateway
            RequestParameters:
              - method.request.path.type:
                  Required: true
  SubmitQuizFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: functions/submit.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: SpotifyQuiz
        - DynamoDBCrudPolicy:
            TableName: SpotifyQuizResponse
      Events:
        GetSubmitQuiz:
          Type: Api
          Properties:
            Path: /submit
            Method: post
            RestApiId: !Ref HttpApiGateway
            RequestParameters:
              - method.request.header.Authorization:
                  Required: true
        OptionsSubmitQuiz:
          Type: Api
          Properties:
            Path: /submit
            Method: options
            RestApiId: !Ref HttpApiGateway
            RequestParameters:
              - method.request.path.type:
                  Required: true

Outputs:
  LoadQuizFunction:
    Description: Python loadQuiz function
    Value: !Ref LoadQuizFunction
  SubmitQuizFunction:
    Description: Python submitQuiz function
    Value: !Ref SubmitQuizFunction
  HttpApiGateway:
    Description: Py Api Gateway
    Value: !Ref HttpApiGateway